function cohort_pvearn_show(loadS, wageConcept, saveFigures, setNo)
% Show time path of lifetime earnings by cohort
%{
IN
   saveS :: struct
      generated by cohort_earn_profiles
      
%}

cS = const_cpsbc(setNo);
% figS = const_fig_bc1;

if wageConcept == cS.iMeanLog
   wcStr = 'meanlog';
else
   wcStr = 'logmedian';
end


%% Levels  and  premium relative to HSG
% Also indicate cohorts used in model
if 1
   yLabelStrV = {'Log present value',  'Lifetime earnings premium'};
   figNameV = {'cohort_pv_lty_',  'cohort_lty_premium_'};
   iSchoolV = cS.iCD : cS.nSchool;
   
   for iPlot = 1 : 2
      % Present values (make into logs), by [cohort, schooling]
      data_csM = log_lh(loadS.pvEarn_scM', cS.missVal);
      if iPlot == 2
         % Relative to HSG
         data_csM = matrix_lh.m_oper(data_csM, repmat(data_csM(:, cS.iHSG), [1, size(data_csM, 2)]),  '-',  ...
            cS.missVal, cS.dbg);
      end

      for iCase = 1 : 2
         fh = output_bc1.plot_by_cohort(loadS.bYearV,  data_csM(:, iSchoolV),  saveFigures, cS);            
      end
      
      ylabel(yLabelStrV{iPlot});
      legend(cS.sLabelV(iSchoolV), 'location', 'northwest');
      output_bc1.fig_format(fh, 'line');
      output_bc1.fig_save([figNameV{iPlot}, wcStr], saveFigures, cS);
   end
end




end